### ISSUE TITLE
HTML5 issue

### ISSUE THREAD

**Issue by AGulev** [britzl/defold-screenshot#1]
I investigated HTML5 issue and found way how to resolve it, thanks stackoverflow: 
https://stackoverflow.com/a/44534528/6389348

preserveDrawingBuffer is bad for performance, but variant with render call before capture call works.
If I add     

`module.buffer, module.w, module.h = screenshot.buffer() `

to the end of update() function  in render_script, and then 
```

if module.buffer then
  resource.set_texture(go.get("cube#model", "texture0"), { type = resource.TEXTURE_TYPE_2D, width = module.w, height = module.h, format = resource.TEXTURE_FORMAT_RGBA }, module.buffer)
end

```
in example update - it works.

I see two ways to solve this issue. 
1. Maybe you know some way to call render update out of turn from native code?
2. Make an async example for html5 that call screenshot.buffer() in the end of of update() of render_script.

**Comment by britzl** [comment]
Fixed in https://github.com/britzl/defold-screenshot/releases/tag/1.6.0
