### ISSUE TITLE
Android. Some devices get black texture instead of screenshot.

### ISSUE THREAD

**Issue by d954mas** [britzl/defold-screenshot#12]
I have 2 devices. In first screenshot worked.
On second i get full black texture instead of screenshot.

Looks like a device specific gpu issue. I have no idea how it can be fixed.

I try google and find that topic..
https://badlogicgames.com/forum/viewtopic.php?t=28801&p=113159
Something bad in glReadPixels function.

Not worked on:
huawei p40

Can you please look on it?
I can test on my device if it can help.

Thanks

**Comment by britzl** [comment]
I'm not entirely sure how to solve it to be honest... The link you shared doesn't really help, unless you render the game to an offscreen buffer and read the pixels from it instead.

**Comment by d954mas** [comment]
Thanks) I also have no idea. Looks like it can't be solved(

**Comment by britzl** [comment]
I think it can be solved by changing the extension to use a callback function on desktop and mobile and grab the screenshot in the POST RENDER callback:

    dmExtension::RegisterCallback(dmExtension::CALLBACK_POST_RENDER, cbk );

I haven't tried this though, but it's worth a shot!

**Comment by d954mas** [comment]
Thanks, i will try it.

**Comment by d954mas** [comment]
Yes it helped. Thanks.
I will make pull request in a weekend. 
![Screenshot_20210116_003124_com d954mas game](https://user-images.githubusercontent.com/2655263/104780696-36bb0500-5792-11eb-9897-a246493fbdde.jpg)

**Comment by britzl** [comment]
That's great!

**Comment by britzl** [comment]
Closed via https://github.com/britzl/defold-screenshot/pull/13
