### ISSUE TITLE
Async callback result is raw pixels

### ISSUE THREAD

**Issue by aglitchman** [britzl/defold-screenshot#15]
The result of `screenshot.png(callback)` should be PNG image, but I get raw pixels.

I think the reason is https://github.com/britzl/defold-screenshot/blob/ab415cdbe3293e88ab780ca00fc112813b803dda/screenshot/src/screenshot_opengl.cpp#L172

**Comment by britzl** [comment]
I'm not getting the extension to build on the latest version of Defold on macOS. Will have to look into this as well.
