### ISSUE TITLE
Feature request: Capturing a part of the game canvas in HTML5

### ISSUE THREAD

**Issue by totebo** [britzl/defold-screenshot#4]
Would be great if a portion of the screen could be captured, rather than the whole canvas. My game is tall so content gets quite small in the context update when the whole screen is used.

**Comment by AGulev** [comment]
Fixed int this PR: https://github.com/britzl/defold-screenshot/pull/5/files
Will be merged soon.

**Comment by AGulev** [comment]
Merged!

**Comment by britzl** [comment]
Released as 1.7.0
