### ISSUE TITLE
The y axis of screenshot.html5() doesn't match Defold's gui.get_position()

### ISSUE THREAD

**Issue by totebo** [britzl/defold-screenshot#7]
From this forum thread:
https://forum.defold.com/t/capturing-a-portion-of-the-screen-with-screenshot-html5/63879/2

**Comment by britzl** [comment]
Please give this branch a try:

https://github.com/britzl/defold-screenshot/tree/dev-invert_html5

**Comment by totebo** [comment]
This works as expected, thanks!

**Comment by d954mas** [comment]
Where is y == 0 should be? Is it top or bottom?
 Same numbers does not create same image in windows and html.
Does not create same images in windows. If y == 0; When i remove that fix all worked. 
screenshot.buffer(x,y, self.w, self.h) 
screenshot.html5(x, y, self.w, self.h)

Thanks

**Comment by britzl** [comment]
You're right. It doesn't produce the same results. I'll look into it!

**Comment by britzl** [comment]
Fixed in new version!
